### ISSUE TITLE
Scripts not loading...

### ISSUE THREAD

**Issue by joex92** [PlaceholderAPI/Javascript-Expansion#39]
ok so my server is using now Java16... idk if that has something to do... but now the scripts are not loading... 

```
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: math
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] ScriptEngine type for javascript placeholder healthbar isn't initialized! Defaulting to global
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] Failed to set ScriptEngine for javascript placeholder: healthbar
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] ScriptEngine type for javascript placeholder playerhealth isn't initialized! Defaulting to global
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] Failed to set ScriptEngine for javascript placeholder: playerhealth
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] File: playercount_inworlds.js for Javascript placeholder: playercount_inworlds is empty
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] ScriptEngine type for javascript placeholder onlineplayerlist isn't initialized! Defaulting to global
[06:10:14] [Server thread/WARN]: [PAPI] [Javascript-Expansion] Failed to set ScriptEngine for javascript placeholder: onlineplayerlist
[06:10:14] [Server thread/INFO]: [PAPI] [Javascript-Expansion] 0 script loaded!
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: javascript
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: statistic
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: sound
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: viaversion
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class com.sk89q.worldguard.WorldGuard from WorldGuard v7.0.4+f7ff984 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class com.sk89q.worldedit.world.World from FastAsyncWorldEdit v1.16-721;f6c87b6 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: worldguard
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] enchantmentbook is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: defaultvalue
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: rainbowcolor
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: playerlist
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: armor
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class github.scarsz.discordsrv.dependencies.google.common.collect.ImmutableMap from DiscordSRV v1.23.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: discordsrv
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] listplayers is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: localtime
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class com.onarandombox.MultiverseCore.MultiverseCore from Multiverse-Core v4.2.3-SNAPSHOT-b836 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: multiverse
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class me.steve8playz.serverwebsite.ServerWebsite from ServerWebsite v5.6 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] ServerWebsite is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: randomcolor
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.3.12 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: Advancements
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.ess3.api.IEssentials from Essentials v2.19.0-dev+157-fa87c74 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: essentials
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: servertime
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: randomcolor
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: geolocation
[06:10:14] [Server thread/WARN]: [PlaceholderAPI] Loaded class me.ryanhamshire.GriefPrevention.GriefPrevention from GriefPrevention v16.17.1-25-g4f95938 which is not a depend, softdepend or loadbefore of this plugin.
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: griefprevention
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: pinger
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: ascii
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: progress
[06:10:14] [Server thread/INFO]: [PlaceholderAPI] [Config Expansion] Loading the configs ...
[06:10:14] [Server thread/ERROR]: [PlaceholderAPI] Task #44177 for PlaceholderAPI v2.10.9 generated an exception
[06:10:14] [Server thread/ERROR]: [PlaceholderAPI] Suspected Plugins:
[06:10:14] [Server thread/ERROR]: [PlaceholderAPI] PlaceholderAPI{enabled,ver=2.10.9,path=plugins/PlaceholderAPI-2.10.9.jar}
[06:10:14] [Server thread/ERROR]: [PlaceholderAPI] Exception details below:
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "me.gabytm.placeholderapi.config.ConfigExpansion.getConfigSection(String)" is null
at me.gabytm.placeholderapi.config.ConfigExpansion.register(ConfigExpansion.java:56) ~[?:?]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:139) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257) ~[?:?]
at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709) ~[?:?]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by Andre601** [comment]
Yes, this has something to do with Java 16.
This was mentioned [on the discord server](https://discord.gg/helpchat) and checking [open PRs](https://github.com/PlaceholderAPI/Javascript-Expansion/pull/38) would've also given a clue about the expansion's current state.

**Comment by joex92** [comment]
so do I go back to Java11? or a new release is coming?

**Comment by Andre601** [comment]
I mentioned the discord server which is a clear place for you to go. You'll find a `#1_17` channel there with more info

**Comment by joex92** [comment]
ok... so those dev builds would work on 1.16.5 too? My server's 1.16.5...

**Comment by darbyjack** [comment]
It has nothing to do with Minecraft version. This is solely based on Java version.
