### ISSUE TITLE
Why does this error occur

### ISSUE THREAD

**Issue by Baikele** [PlaceholderAPI/Javascript-Expansion#58]
`
[21:16:52] [Server thread/ERROR]: [PlaceholderAPI] Failed to load expansion class JavascriptExpansion (Is a dependency missing?)
[21:16:52] [Server thread/ERROR]: [PlaceholderAPI]
java.lang.NoClassDefFoundError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory
        at com.extendedclip.papi.expansion.javascript.evaluator.NashornScriptEvaluatorFactory.create(NashornScriptEvaluatorFactory.java:34) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.createNashornEvaluatorFactory(JavascriptExpansion.java:176) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.register(JavascriptExpansion.java:97) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:172) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_301]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_301]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:333) ~[?:?]
        at me.clip.placeholderapi.util.Futures.lambda$onMainThread$0(Futures.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [CraftTask.class:git-CatServer-1.12.2-c0537be]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-c0537be]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:882) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.ClassNotFoundException: Failed to remap class org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory
        at catserver.server.remapper.target.CatURLClassLoader.remappedFindClass(CatURLClassLoader.java:142) ~[CatURLClassLoader.class:git-CatServer-1.12.2-c0537be]
        at catserver.server.remapper.target.CatURLClassLoader.findClass(CatURLClassLoader.java:65) ~[CatURLClassLoader.class:git-CatServer-1.12.2-c0537be]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 21 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228) ~[JarRemapper.class:?]
        at catserver.server.remapper.target.CatURLClassLoader.remappedFindClass(CatURLClassLoader.java:107) ~[CatURLClassLoader.class:git-CatServer-1.12.2-c0537be]
        at catserver.server.remapper.target.CatURLClassLoader.findClass(CatURLClassLoader.java:65) ~[CatURLClassLoader.class:git-CatServer-1.12.2-c0537be]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 21 more
`

1.12.2 java8
https://paste.helpch.at/xokesajeta

**Comment by JuDasPerge** [comment]
Hey, i have the same issue :/
I'm on java 17 and minecraft-1.17.

**Comment by darbyjack** [comment]
Have you tried switching to quick-js in the config?

**Comment by Baikele** [comment]
> 您是否尝试过在配置中切换到 quick-js？

    use_quick_js: true?

**Comment by Baikele** [comment]
> 您是否尝试过在配置中切换到 quick-js？

![1644112422](https://user-images.githubusercontent.com/70128689/152665043-62faf761-7a63-44a4-a0be-9d4bea7c452b.png)
![image](https://user-images.githubusercontent.com/70128689/152665048-64b53346-032d-4863-af5d-b01ec610a848.png)


why is that
