### ISSUE TITLE
Issue on reload

### ISSUE THREAD

**Issue by smuddgge** [PlaceholderAPI/Javascript-Expansion#71]
```
[10:14:09 ERROR]: [PlaceholderAPI] Failed to load expansion class JavascriptExpansion (Is a dependency missing?)
java.lang.NoClassDefFoundError: Could not initialize class com.koushikdutta.quack.QuackContext
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluator.execute(QuickJsScriptEvaluator.java:17) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluatorFactory.attemptBasicEvaluation(QuickJsScriptEvaluatorFactory.java:43) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluatorFactory.createWithFallback(QuickJsScriptEvaluatorFactory.java:35) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.register(JavascriptExpansion.java:92) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:191) ~[PlaceholderAPI 2.11.2.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandExpansionRegister.lambda$evaluate$0(CommandExpansionRegister.java:79) ~[PlaceholderAPI 2.11.2.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI 2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/quickjs-1.0.0/libquickjs.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/quickjs-1.0.0/libquickjs.so) [in thread "Server thread"]
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:785) ~[?:?]
        at java.lang.System.load(System.java:2011) ~[?:?]
        at com.koushikdutta.quack.QuackContext.loadJni(QuackContext.java:100) ~[PlaceholderAPI 2.11.2.jar:?]
        at com.koushikdutta.quack.QuackContext.<clinit>(QuackContext.java:74) ~[PlaceholderAPI 2.11.2.jar:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluator.execute(QuickJsScriptEvaluator.java:17) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluatorFactory.attemptBasicEvaluation(QuickJsScriptEvaluatorFactory.java:43) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.QuickJsScriptEvaluatorFactory.createWithFallback(QuickJsScriptEvaluatorFactory.java:35) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.register(JavascriptExpansion.java:92) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:191) ~[PlaceholderAPI 2.11.2.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:350) ~[PlaceholderAPI 2.11.2.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI 2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[purpur-1.19.2.jar:git-Purpur-1835]
        ... 2 more
```
<img width="897" alt="Screenshot 2022-11-08 at 10 16 37" src="https://user-images.githubusercontent.com/68658429/200538410-d7fc7b91-5f11-4ac2-b238-315adcdc7c4c.png">

**Comment by smuddgge** [comment]
Has been sorted, was to do with the docker
