### ISSUE TITLE
java.nio.file.AccessDeniedException: /home/container/plugins/PlaceholderAPI/javascripts/javascript_data

### ISSUE THREAD

**Issue by AltuYumusakG** [PlaceholderAPI/Javascript-Expansion#79]
[23:27:10 INFO]: AltuYumusakG issued server command: /papi reload
[23:27:10 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[23:27:10 INFO]: [PlaceholderAPI] Fetching available expansion information...
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: server [2.6.2]
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: statistic [2.0.1]
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: player [2.0.8]
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: luckperms [5.4-R2]
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: bungee [2.3]
[23:27:11 INFO]: [PlaceholderAPI] Successfully registered external expansion: utils [1.0.7]
[23:27:11 ERROR]: [PAPI] [Javascript-Expansion] Unable to create placeholder data file
java.nio.file.AccessDeniedException: /home/container/plugins/PlaceholderAPI/javascripts/javascript_data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:699) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.script.data.YmlPersistableData.create(YmlPersistableData.java:53) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptPlaceholder.<init>(JavascriptPlaceholder.java:66) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.SimpleJavascriptPlaceholderFactory.create(SimpleJavascriptPlaceholderFactory.java:16) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.script.ConfigurationScriptLoader.reload(ConfigurationScriptLoader.java:38) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.register(JavascriptExpansion.java:121) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:193) ~[PlaceholderAPI-2.11.5.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366) ~[PlaceholderAPI-2.11.5.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI-2.11.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1481) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1395) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:1595) ~[?:?]
[23:27:11 WARN]: [PlaceholderAPI] Task #31962 for PlaceholderAPI v2.11.5 generated an exception
java.lang.RuntimeException: java.nio.file.AccessDeniedException: /home/container/plugins/PlaceholderAPI/javascripts/javascript_data
        at com.extendedclip.papi.expansion.javascript.JavascriptPlaceholder.<init>(JavascriptPlaceholder.java:69) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.SimpleJavascriptPlaceholderFactory.create(SimpleJavascriptPlaceholderFactory.java:16) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.script.ConfigurationScriptLoader.reload(ConfigurationScriptLoader.java:38) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.register(JavascriptExpansion.java:121) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:193) ~[PlaceholderAPI-2.11.5.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366) ~[PlaceholderAPI-2.11.5.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI-2.11.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1481) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1395) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:1595) ~[?:?]
Caused by: java.nio.file.AccessDeniedException: /home/container/plugins/PlaceholderAPI/javascripts/javascript_data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:699) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.script.data.YmlPersistableData.create(YmlPersistableData.java:53) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptPlaceholder.<init>(JavascriptPlaceholder.java:66) ~[?:?]
        ... 22 more

**Comment by regix1** [comment]
same issue
